### ISSUE TITLE
DIAG_JUMPERS_REMOVED

### ISSUE THREAD

**Issue by markvarvel** [brianvoo/BIGTREETECH-SKR-MINI-E3-V3-BLTouch-ZHoming#1]
In file configuration.h

The following needs to be added to compile.
I suggest placing it here:
// @section machine
#define DIAG_JUMPERS_REMOVED

Thank you

**Comment by brianvoo** [comment]
A warning does appear without #define DIAG_JUMPERS_REMOVED, but I am able to compile without any issues.
